# Generated by Django 2.1 on 2019-05-26 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0004_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
